server:
    port: 8080

spring:
    profiles:
        active: prod
        cassandra:
            host: localhost
            protocolVersion: 2
            keyspaceName: jhipster

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: true

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: jhipster


